### ISSUE TITLE
Use Types in Request Body of the Route Hander

### ISSUE THREAD

**Issue by realnsleo** [ryands17/fastify-prisma#75]
Hello Ryan,
Thanks so much for this skeleton. I am using it in my project. I have just one question. I am trying to pass certain variables in my Request Body. In your implementation, you had this like `request.body as any`. I read through the Fastify documentation and I zeroed down to something like:
```ts
    type AuthLoginBodyRequest = FastifyRequest<{
      Body: {
        phone_number: string,
        password: string
      };
    }>

    export const login: RouteHandlerMethod = async (request: AuthLoginBodyRequest , reply) => {
      const { phone_number, password } = request.body;

      // Login code which eventually returns a user object

      return reply.send({ user });
    };
```
However, this is not working for me. I get the error below:

    TSError: ⨯ Unable to compile TypeScript:
    src/controllers/auth.ts:14:14 - error TS2322: Type '(this: FastifyInstance<...>, request: AuthLoginBodyRequest, reply: 
      FastifyReply<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown>) => Promise<...>' is not assignable to type 'RouteHandlerMethod<Server, IncomingMessage, ServerResponse, RouteGenericInterface, unknown>'.
        Types of parameters 'request' and 'request' are incompatible.
          Type 'FastifyRequest<RouteGenericInterface, Server, IncomingMessage>' is not assignable to type 'AuthLoginBodyRequest'.
            Type 'RouteGenericInterface' is not assignable to type '{ Body: { phone_number: string; password: string; }; }'.
              Types of property 'Body' are incompatible.
                Type 'unknown' is not assignable to type '{ phone_number: string; password: string; }'.

Any ideas as to why this could be happening? I will be very grateful!
14 export const login: RouteHandlerMethod = async (request: AuthLoginBodyRequest, reply) => {

**Comment by ryands17** [comment]
@realnsleo 👋 

Let me check and get back to you on this 🙂

**Comment by ryands17** [comment]
I think you need to do something like this instead of assigning the `request` directly:

```ts
type PostBody = {
  username: string
  password: string
}

type PostType = {
  Body: PostBody
}

app.post<PostType>('/signup', async (req, res) => {
  // typings should work here
  req.body.username
})
```
